"""Ilk kurulum

Revision ID: 948e366dfe3b
Revises: 
Create Date: 2026-01-11 15:09:10.335124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948e366dfe3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    op.drop_table('topic')
    op.drop_table('progress')
    op.drop_table('classroom')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('classroom',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('classroom_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('teacher_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='classroom_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('progress_student_id_fkey')),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name=op.f('progress_topic_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('progress_pkey'))
    )
    op.create_table('topic',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('is_covered', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('classroom_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], name=op.f('topic_classroom_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('topic_pkey'))
    )
    op.create_table('enrollments',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('classroom_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], name=op.f('enrollments_classroom_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('enrollments_student_id_fkey'))
    )
    # ### end Alembic commands ###
